project_name: "taskcluster-auth"
secrets:
  aws_access_key_id: ".Values.authAwsAccessKeyId"
  aws_region: ".Values.tfAwsRegion"
  aws_secret_access_key: ".Values.authAwsSecretAccessKey"
  azure_account: ".Values.tfAzureAccount"
  azure_accounts: ".Values.azureAccounts"
  azure_account_key: ".Values.azureAccountKey"
  azure_crypto_key: ".Values.authAzureCryptoKey"
  azure_signing_key: ".Values.authAzureSigningKey"
  force_ssl: "false"
  lock_roles: "false"
  node_env: "production"
  profile: "production"
  pulse_hostname: ".Values.tfRabbitmqHostname"
  pulse_password: ".Values.authPulsePassword"
  pulse_username: ".Values.authPulseUsername"
  pulse_vhost: ".Values.pulseVhost"
  static_clients: ".Values.staticClients"
  trust_proxy: "true"
  websocktunnel_secret: ".Values.websocktunnelSecret"
        
deployments:
  - service_name: "auth"
    docker_image: ".Values.dockerImage"
    proc_name: "web"
    readiness_path: "/api/auth/v1/ping"
    root_url: ".Values.rootUrl"
cronjobs:
  - service_name: "auth"
    deadline_seconds: 86400
    docker_image: ".Values.dockerImage"
    job_name: "purgeExpiredClients"
    root_url: ".Values.rootUrl"
    schedule: "0 0 * * *"
