project_name: "taskcluster-hooks"
secrets:
  azure_account: ".Values.tfAzureAccount"
  force_ssl: "false"
  hook_table_name: "Hooks"
  lastfire_table_name: "LastFire2"
  node_env: "production"
  pulse_hostname: ".Values.tfRabbitmqHostname"
  pulse_password: ".Values.hooksPulsePassword"
  pulse_username: ".Values.hooksPulseUsername"
  pulse_vhost: ".Values.pulseVhost"
  queue_table_name: "Queue"
  table_crypto_key: ".Values.hooksTableCryptoKey"
  table_signing_key: ".Values.hooksTableSigningKey"
  taskcluster_access_token: ".Values.hooksAccessToken"
  taskcluster_client_id: "static/taskcluster/hooks"
  trust_proxy: "true"
deployments:
  - service_name: "hooks"
    docker_image: ".Values.dockerImage"
    proc_name: "web"
    readiness_path: "/api/hooks/v1/ping"
    root_url: ".Values.rootUrl"
  - service_name: "hooks"
    background_job: true
    docker_image: ".Values.dockerImage"
    proc_name: "scheduler"
    root_url: ".Values.rootUrl"
  - service_name: "hooks"
    background_job: true
    docker_image: ".Values.dockerImage"
    proc_name: "listeners"
    root_url: ".Values.rootUrl"
cronjobs:
  - service_name: "hooks"
    deadline_seconds: 86400
    docker_image: ".Values.dockerImage"
    job_name: "expires"
    root_url: ".Values.rootUrl"
    schedule: "10 0 * * *"
